<script setup lang="ts"></script>
<template>
  <UApp>
    <UContainer>
      <NuxtPage />
      <div class="text-center"></div>
      <div class="text-center text-pretty flex justify-center flex-wrap">
        <UIcon name="uil-robot" class="size-6 mr-2" />
        Questions were generated by AI and may contain inaccuracies.
        <p>
          You can click on "Report Question" if you think there's something wrong with the current question.
        </p>
      </div>
    </UContainer>
  </UApp>
</template>
